default_platform(:android)

platform :android do

  private_lane :increment_version do |options|
     puts "increments versions #{options}"
     android_set_version_code(
       gradle_file: "app/build.gradle.kts",
       version_code: options[:version_code]
     )
  end

  desc "Run unit tests"
  lane :test do
    gradle(task: "testDevDebugUnitTest")
  end

  desc "Run UI tests (requires a connected device or emulator)"
  lane :ui_test do
    gradle(
      task: "assembleDevDebug assembleDevDebugAndroidTest"
    )
    sh("gcloud --project=offlinegpt-dev firebase test android run --type instrumentation --app /home/runner/work/offline_gpt/offline_gpt/app/build/outputs/apk/dev/debug/app-dev-debug.apk --test /home/runner/work/offline_gpt/offline_gpt/app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk --device model=oriole,version=33,locale=en,orientation=portrait --results-bucket=mactest")
  end

 desc "Run UI tests (requires a connected device or emulator)"
  lane :ui_test_qa do
    gradle(
      task: "assembleDevDebug assembleDevDebugAndroidTest"
    )
    sh("gcloud --project=offlinegpt-qa firebase test android run --type instrumentation --app /home/runner/work/offline_gpt/offline_gpt/app/build/outputs/apk/dev/debug/app-dev-debug.apk --test /home/runner/work/offline_gpt/offline_gpt/app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk --device model=oriole,version=33,locale=en,orientation=portrait --results-bucket=mactest2")
  end

  desc "Submit a new Dev Build to Firebase App Distribution"
  lane :distribute_dev do
    app_id = ENV["FIREBASE_APP_ID_DEV"]
    UI.user_error!("FIREBASE_APP_ID_DEV environment variable is empty") if app_id.to_s.empty?

    # 0. Run tests
    test
    # 1. Get the latest build number from Firebase
    begin
      latest_release = firebase_app_distribution_get_latest_release(app: app_id)
      latest_build_number = latest_release ? latest_release[:buildVersion].to_i : 0
    rescue => e
      UI.important("Could not fetch latest release from Firebase (maybe no builds yet?): #{e.message}")
      latest_build_number = 0
    end
    UI.message("latest_release on Firebase: #{latest_release}")
    UI.message("Latest Build ID on Firebase: #{latest_build_number}")

    # 2. Increment
    new_build_number = latest_build_number + 1
    UI.message("Next Build ID: #{new_build_number}")

    # 3. Update local build.gradle.kts (optional, but requested via increment_version)
    increment_version(version_code: new_build_number)

    gradle(
      task: "assembleDevRelease",
      properties: {
        "android.injected.versionCode" => new_build_number
      }
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_DEV"],
      apk_path: "/home/runner/work/offline_gpt/offline_gpt/app/build/outputs/apk/dev/release/app-dev-release.apk",
      groups: "testers",
      release_notes: "Dev build #{new_build_number} from Fastlane"
    )
  end

  desc "Submit a new QA Build to Firebase App Distribution"
  lane :distribute_qa do

    test
    ui_test_qa
    app_id = ENV["FIREBASE_APP_ID_QA"]
    UI.user_error!("FIREBASE_APP_ID_QA environment variable is empty") if app_id.to_s.empty?

    begin
      latest_release = firebase_app_distribution_get_latest_release(app: app_id)
      latest_build_number = latest_release ? latest_release[:buildVersion].to_i : 0
    rescue => e
      UI.important("Could not fetch latest release from Firebase (maybe no builds yet?): #{e.message}")
      latest_build_number = 0
    end
    UI.message("latest_release on Firebase: #{latest_release}")
        UI.message("Latest Build ID on Firebase: #{latest_build_number}")

        # 2. Increment
        new_build_number = latest_build_number + 1
        UI.message("Next Build ID: #{new_build_number}")

        # 3. Update local build.gradle.kts (optional, but requested via increment_version)
        increment_version(version_code: new_build_number)


    gradle(
      task: "assembleQaRelease",
      properties: {
        "android.injected.versionCode" => new_build_number
      }
    )


    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_QA"],
      apk_path: "/home/runner/work/offline_gpt/offline_gpt/app/build/outputs/apk/qa/release/app-qa-release.apk",
      groups: "testers",
      release_notes: "QA build from Fastlane"
    )
  end

  desc "Submit a new Prod Build to Firebase App Distribution"
  lane :distribute_prod do
    app_id = ENV["FIREBASE_APP_ID_PROD"]
    UI.user_error!("FIREBASE_APP_ID_PROD environment variable is empty") if app_id.to_s.empty?

    begin
      latest_release = firebase_app_distribution_get_latest_release(app: app_id)
      latest_build_number = latest_release ? latest_release[:buildVersion].to_i : 0
    rescue => e
      UI.important("Could not fetch latest release from Firebase (maybe no builds yet?): #{e.message}")
      latest_build_number = 0
    end
    UI.message("latest_release on Firebase: #{latest_release}")
        UI.message("Latest Build ID on Firebase: #{latest_build_number}")

        # 2. Increment
        new_build_number = latest_build_number + 1
        UI.message("Next Build ID: #{new_build_number}")

        # 3. Update local build.gradle.kts (optional, but requested via increment_version)
        increment_version(version_code: new_build_number)


    gradle(
      task: "assembleProdRelease",
      properties: {
        "android.injected.versionCode" => new_build_number
      }
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_PROD"],
      apk_path: "/home/runner/work/offline_gpt/offline_gpt/app/build/outputs/apk/prod/release/app-prod-release.apk",
      groups: "testers",
      release_notes: "Prod release build from Fastlane"
    )
  end
end
